### ISSUE TITLE
Replace Walker::to_caret with Walker::to_caret_safe everywhere

### ISSUE THREAD

**Issue by tcr** [tcr/edit-text#113]
`edit-client/src/walkers.rs` has a class Walker and it has two nearly identical methods, to_caret and to_caret_safe. The latter returns an option, while the former panics. The former, in every place it is called, can be replaced by to_caret_safe().unwrap().

By replacing all of them, we can delete to_caret and rename to_caret_safe to to_caret.

**Comment by briankabiro** [comment]
Hey Tim; hope you've been doing okay. Would like to pick this up!

**Comment by tcr** [comment]
@briankabiro Hey! Sorry I didn't see this comment sooner, it got buried in my notifications. This issue is actually out of date as of 9c78e76. I'm working on creating new entry-level issues though and updating the docs at http://docs.edit.io/.

I opened the issue #229 just now if you wanted to take a look. It's a small feature but it should be similar in scope to this issue, plus it'll be the basis for an "open new document" button on the frontend eventually. I'll open a few easy issues over the weekend that you're welcome to try out as well.

**Comment by briankabiro** [comment]
Hey Tim, no worries! Know that it can get hard to keep up with them notifications at times.

Thanks for the referral and also for the new issues; I'll be sure to check #229 out. 😃
