### ISSUE TITLE
Block buttons should highlight depending on which block type you are currently in

### ISSUE THREAD

**Issue by tcr** [tcr/edit-text#24]
When you are in a `Heading 1` block, that box should be highlighted (in bold) and the rest should not be. etc.

**Comment by briankabiro** [comment]
Hey, @tcr. Has this been taken up?

**Comment by tcr** [comment]
@briankabiro Hey! Unfortuantely it has (live on http://sandbox.edit.io/) and I've been bad at issue maintenance. Thanks for surfacing this.

I opened another good first issue task, in case that's what you were looking for: #44

There is also a follow up task to this available about making the "highlight button when caret is inside it" logic less expensive. Right now it's called for every document change and this computes some things twice. By avoiding the recomputation, it should speed up all client changes.

**Comment by briankabiro** [comment]
Oh, thanks. I was looking for a good first issue task. I'll checkout #44 to get acquainted with the codebase and then ease my way to the follow-up task.

**Comment by briankabiro** [comment]
Hey, @tcr. Referencing `There is also a follow up task to this available about making the "highlight button when caret is inside it" logic less expensive.`. Could you provide more context on that, or would it be better to open an issue for it? 😃

**Comment by tcr** [comment]
@briankabiro I've opened a new issue with first steps!

https://github.com/tcr/edit-text/issues/51

Making the "figure out the button state logic" where `identify_block` is called in client.rs is still expensive, but the first step is to reduce how much data we're sending to the client. This should drop the WebAssembly <-> JavaScript traffic by half.

I'll follow up with other tasks related to this shortly, but hopefully this is a good start. Thanks for your first PR also :)

**Comment by briankabiro** [comment]
Thanks, @tcr for the prompt response. I've checked out the issue and can take it up. 
Also about the first PR, no biggie. 👍
