### ISSUE TITLE
Support H4-H6 as well

### ISSUE THREAD

**Issue by tcr** [tcr/edit-text#44]
Since the goal of the editor is to be compatible with Markdown, this means we'll need to support H1-H6 (the editor currently supports H1, H2, and H3).

This should be straightforward, as in just duplicating the code for H1 H2 and H3 that lives in mercutio-client.

**Comment by briankabiro** [comment]
Hey, @tcr. Just wanted to get some clarification on this. Is it duplicating the code in the `Button Handler` section just like it's been done for `h1, h2, h3`?

**Comment by tcr** [comment]
@briankabiro Yeah! So to run down the list of what would need support added, it would be:

1. Add a new entry in the button handler, as you mention, similar to `h1, h2, h3`
2. Add support in the [schema.rs](https://github.com/tcr/edit-text/blob/d104a6a366f1fec609cc5d1507b4942a1699f6e1/oatie/src/schema.rs) file for identifying `h4, h5, h6` as the RtfTrack::Blocks blocks type
3. Modify the markdown [serialize](https://github.com/tcr/edit-text/blob/59d1dbf75e181d9de1e429d66f86a99f3c6d1015/mercutio-common/src/markdown/ser.rs) and [deserialize](https://github.com/tcr/edit-text/blob/59d1dbf75e181d9de1e429d66f86a99f3c6d1015/mercutio-common/src/markdown/de.rs) methods for supporting `h4, h5, h6`.

Incidentally, it looks like steps 2 and 3 are already done, so only #1 is left to do.

A stress test of using this is to run the server and client locally (`./x.rs server --client-proxy` and in a separate tab `./x.rs client-proxy`) and then navigate to http://localhost:8000/$/multi/, which will display three clients at once, and click the `🙈🙉🙊` button at the top, which will hit buttons at random. This will stress-test the new button entries and make sure there's no surprising behavior after adding `h4, h5, h6` support. For example, if the schema did not recognize these values, but there were buttons for it, it would panic. I believe there's no risk of that happening here, but still worth checking.

Let me know if I can add any more detail to these steps. An issue I haven't opened yet (but intend to) would be to add `blockquote` support, for which steps 1, 2, and 3 would need to be followed, since there's no support yet. I can open that issue if it's interesting.

**Comment by briankabiro** [comment]
Hey, thanks for the clarification. I've looked into it and added the entries in the `Button Handler`. 
I also ran the stress test after making the changes and opened a PR just now.
Also, +1 on adding the `blockquote` issue, I could check it out later on. 😃   
I'll read up on the steps you outlined above so that I can get a feel of how to do that.

**Comment by tcr** [comment]
All set :)
